// itemSpecs.js — authoritative per-item customer (and species/channel) from the
// "Product Specs Data.xlsx" export, loaded from reference/item-specs.json
// (regenerated by scripts/import-item-specs.py and committed, so it deploys with
// the code — it is NOT under the gitignored data/).
//
// Used in the customer-attribution chain (backend/production.js):
//     manual transfer  >  spec-sheet customer (here)  >  notes/description guess
// i.e. this authoritative per-code customer beats the heuristic parseCustomer
// guess, but a deliberate manual transfer still wins.
//
// The sheet uses long names ("MISHIMA RESERVE", "GILLUM FAMILY FARMS"); the rest
// of the app uses short canonical names ("Mishima", "GFF"). We canonicalize at
// load via ALIAS below so rollups merge with the existing customers. Names not in
// ALIAS become a Title-Cased customer of their own — edit ALIAS to fold any of
// them into an existing account.

const fs = require('fs');
const path = require('path');

const FILE = path.join(__dirname, '..', 'reference', 'item-specs.json');

// Spec-sheet customer (UPPER-CASE) → the app's canonical customer name. Only the
// ones that map onto an EXISTING canonical customer need an entry; everything
// else is Title-Cased into its own account.
const ALIAS = {
  'JD FOOD': 'JD Food',
  'MISHIMA RESERVE': 'Mishima',
  'GOURMET BEEF': 'Gourmet',
  'EEL RIVER': 'Eel River',
  'MARIPOSA RANCH': 'Mariposa',
  'GILLUM FAMILY FARMS': 'GFF',
  'AJINOMOTO WINDSOR': 'Ajinomoto',
  'DIESTEL': 'Diestel',
  'HARRIS RANCH': 'Harris Ranch',
  'MIAMI BEEF': 'Miami',
  'HEWITT FOODS': 'Hewitt',
  'JOURNEYMAN MEAT CO.': 'JMC',
  'WHOLE FOODS': 'WFM',
  'BRANDT': 'Brandt',
  'MCI': 'MCI',
  // 'BIRITE': 'JD Food',  // ← the old heuristic folded Birite into JD Food. The
  //   spec sheet tags it as its own account (81 items), so it now rolls up as
  //   "Birite". Uncomment this line to merge it back into JD Food.
};

const titleCase = (s) => s.toLowerCase().replace(/\b([a-z])/g, (m) => m.toUpperCase());
function canonCustomer(raw) {
  const up = String(raw == null ? '' : raw).trim().toUpperCase();
  if (!up) return null;
  return ALIAS[up] || titleCase(up);
}

let byCode = new Map();      // code -> { customer (canonical), species, channel }
let customers = [];          // sorted unique canonical customers seen in the sheet
let fingerprint = 'specs:0'; // changes when the dataset changes → invalidates stored summaries

function load() {
  try {
    const data = JSON.parse(fs.readFileSync(FILE, 'utf8'));
    const items = data.items || {};
    const m = new Map();
    const set = new Set();
    for (const [code, rec] of Object.entries(items)) {
      const customer = canonCustomer(rec.customer);
      if (!customer) continue;
      m.set(String(code).trim(), { customer, species: rec.species || null, channel: rec.channel || null });
      set.add(customer);
    }
    byCode = m;
    customers = [...set].sort((a, b) => (a < b ? -1 : a > b ? 1 : 0));
    fingerprint = `specs:${m.size}@${data.generatedAt || ''}`;
    console.log(`[ItemSpecs] loaded ${m.size} item→customer mappings (${customers.length} customers) from ${data.generatedAt || 'reference'}`);
  } catch (e) {
    if (e.code !== 'ENOENT') console.error('[ItemSpecs] load failed:', e.message);
    else console.warn('[ItemSpecs] reference/item-specs.json not found — spec-sheet attribution disabled');
    byCode = new Map(); customers = []; fingerprint = 'specs:0';
  }
}

load();

const getCustomer = (code) => { const r = byCode.get(String(code).trim()); return r ? r.customer : null; };
const get = (code) => byCode.get(String(code).trim()) || null;
const getCustomers = () => customers.slice();

module.exports = { getCustomer, get, getCustomers, get fingerprint() { return fingerprint; }, get size() { return byCode.size; } };
